### PR TITLE
Optimize the image catalogue server call

### PR DESCRIPTION
**Pull request by Blistin**
Remove the constant Parse calls when scrolling the image view and cache the images using an array of objects similar to the Flicks app.

### CODE REVIEW

**Comment by Blistin** [comment]
The optimization appears to make the image catalog much more smooth but I noticed two issues while testing:
- Sending an image w/o a tag now crashes Gaia
- Capturing a new image does not refresh the catalog to show the new image

**Comment by Blistin** [comment]
@jlhbaseball15 try to take care of these but the performance looks much better once these bugs are squashed

**Comment by johnhenning** [comment]
It shouldn't be able to send an image if the tag is blank. So when the tag == "", it should gray out save or something

**Comment by Blistin** [comment]
Were you able to fix the refresh of the catalog on saving a new image?

**Comment by johnhenning** [comment]
Not yet. I can't really test it without an iPhone

**Pull request merged**
